#
# Drone pipeline push code to github.
#

kind: pipeline
type: docker
name: default


steps:
# - name: push commit
#   image: appleboy/drone-git-push
#   settings:
#     branch: master
#     remote: git@github.com:slimylove/scripts.git
#     force: false
#     commit: false
- name: push-github
  image: alpine/git
  commands:
  - git status
  - ls
