#
# Drone pipeline push code to github.
#

kind: pipeline
type: docker
name: default


steps:
# - name: push commit
#   image: appleboy/drone-git-push
#   settings:
#     branch: master
#     remote: git@github.com:slimylove/scripts.git
#     force: false
#     commit: false
- name: push-github
  image: alpine/git
  # volumes:
  # - name: ssh
  #   path: ~/.ssh
  commands:
  - git status
  - git remote add github git@github.com:slimylove/scripts.git
  # - cat ~/.ssh/id_rsa.pub
  # - echo yes | git push github dev
  when:
    branch:
    - dev
- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote_name: github
    branch: dev
    ssh_key:
      from_secret: ssh_key
  commands:
  - cat ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub
  when:
    branch:
    - dev

# volumes:
# - name: ssh
#   host: 
#     path: ~/.ssh